/*
 * Oktawave API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.oktawave.api.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * Assign new monitoring sensor command
 */
@ApiModel(description = "Assign new monitoring sensor command")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-02-03T15:23:33.358+01:00")
public class AssignNewMonitoringSensorCommand {
  @SerializedName("SensorId")
  private Integer sensorId = null;

  public AssignNewMonitoringSensorCommand sensorId(Integer sensorId) {
    this.sensorId = sensorId;
    return this;
  }

   /**
   * Sensor id
   * @return sensorId
  **/
  @ApiModelProperty(required = true, value = "Sensor id")
  public Integer getSensorId() {
    return sensorId;
  }

  public void setSensorId(Integer sensorId) {
    this.sensorId = sensorId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AssignNewMonitoringSensorCommand assignNewMonitoringSensorCommand = (AssignNewMonitoringSensorCommand) o;
    return Objects.equals(this.sensorId, assignNewMonitoringSensorCommand.sensorId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sensorId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AssignNewMonitoringSensorCommand {\n");

      sb.append("    sensorId: ").append(toIndentedString(sensorId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

