/*
 * Oktawave API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.oktawave.api.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * Attach IP to instance command
 */
@ApiModel(description = "Attach IP to instance command")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-02-03T15:23:33.358+01:00")
public class AttachIpToInstanceCommand {
  @SerializedName("IpId")
  private Integer ipId = null;

  @SerializedName("IpV6")
  private Boolean ipV6 = null;

  public AttachIpToInstanceCommand ipId(Integer ipId) {
    this.ipId = ipId;
    return this;
  }

   /**
   * IP address identifier. Optional value, if null random ip will be attached.
   * @return ipId
  **/
  @ApiModelProperty(value = "IP address identifier. Optional value, if null random ip will be attached.")
  public Integer getIpId() {
    return ipId;
  }

  public void setIpId(Integer ipId) {
    this.ipId = ipId;
  }

  public AttachIpToInstanceCommand ipV6(Boolean ipV6) {
    this.ipV6 = ipV6;
    return this;
  }

   /**
   * If attach IPv6 only. Optional value, if null IPv4 and IPv6 will be attached.
   * @return ipV6
  **/
  @ApiModelProperty(value = "If attach IPv6 only. Optional value, if null IPv4 and IPv6 will be attached.")
  public Boolean isIpV6() {
    return ipV6;
  }

  public void setIpV6(Boolean ipV6) {
    this.ipV6 = ipV6;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AttachIpToInstanceCommand attachIpToInstanceCommand = (AttachIpToInstanceCommand) o;
    return Objects.equals(this.ipId, attachIpToInstanceCommand.ipId) &&
        Objects.equals(this.ipV6, attachIpToInstanceCommand.ipV6);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ipId, ipV6);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AttachIpToInstanceCommand {\n");

      sb.append("    ipId: ").append(toIndentedString(ipId)).append("\n");
    sb.append("    ipV6: ").append(toIndentedString(ipV6)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

