/*
 * Oktawave API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.oktawave.api.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Change container assignments Command
 */
@ApiModel(description = "Change container assignments Command")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-04-25T12:05:03.973+02:00")
public class ChangeContainerAssignmentsCommand {
  @SerializedName("Assignments")
  private List<ContainerAssignmentCommand> assignments = null;

  public ChangeContainerAssignmentsCommand assignments(List<ContainerAssignmentCommand> assignments) {
    this.assignments = assignments;
    return this;
  }

  public ChangeContainerAssignmentsCommand addAssignmentsItem(ContainerAssignmentCommand assignmentsItem) {
    if (this.assignments == null) {
      this.assignments = new ArrayList<ContainerAssignmentCommand>();
    }
    this.assignments.add(assignmentsItem);
    return this;
  }

   /**
   * Get assignments
   * @return assignments
  **/
  @ApiModelProperty(value = "")
  public List<ContainerAssignmentCommand> getAssignments() {
    return assignments;
  }

  public void setAssignments(List<ContainerAssignmentCommand> assignments) {
    this.assignments = assignments;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChangeContainerAssignmentsCommand changeContainerAssignmentsCommand = (ChangeContainerAssignmentsCommand) o;
    return Objects.equals(this.assignments, changeContainerAssignmentsCommand.assignments);
  }

  @Override
  public int hashCode() {
    return Objects.hash(assignments);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChangeContainerAssignmentsCommand {\n");
    
    sb.append("    assignments: ").append(toIndentedString(assignments)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

