/*
 * Oktawave API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.oktawave.api.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.threeten.bp.OffsetDateTime;

import java.util.Objects;

/**
 * Create/update instance scheduler command
 */
@ApiModel(description = "Create/update instance scheduler command")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-02-03T15:23:33.358+01:00")
public class CreateUpdateInstanceSchedulerCommand {
  @SerializedName("Name")
  private String name = null;

  @SerializedName("TypeId")
  private Integer typeId = null;

  @SerializedName("StartDate")
  private OffsetDateTime startDate = null;

    @SerializedName("TimeZoneName")
    private String timeZoneName = null;

  @SerializedName("CycleTypeId")
  private Integer cycleTypeId = null;

  @SerializedName("CycleNumber")
  private Integer cycleNumber = null;

  @SerializedName("ActionTypeId")
  private Integer actionTypeId = null;

  @SerializedName("NewInstanceTypeId")
  private Integer newInstanceTypeId = null;

  @SerializedName("SnapshotName")
  private String snapshotName = null;

  @SerializedName("SnapshotDescription")
  private String snapshotDescription = null;

  @SerializedName("SnapshotId")
  private Integer snapshotId = null;

  @SerializedName("CloneName")
  private String cloneName = null;

  @SerializedName("StoragePath")
  private String storagePath = null;

  @SerializedName("StorageProjectId")
  private String storageProjectId = null;

  @SerializedName("IsBackupsDaysLimit")
  private Boolean isBackupsDaysLimit = null;

  @SerializedName("BackupsDaysLimit")
  private Integer backupsDaysLimit = null;

  public CreateUpdateInstanceSchedulerCommand name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name
   * @return name
  **/
  @ApiModelProperty(required = true, value = "Name")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public CreateUpdateInstanceSchedulerCommand typeId(Integer typeId) {
    this.typeId = typeId;
    return this;
  }

   /**
   * Type id
   * @return typeId
  **/
  @ApiModelProperty(required = true, value = "Type id")
  public Integer getTypeId() {
    return typeId;
  }

  public void setTypeId(Integer typeId) {
    this.typeId = typeId;
  }

  public CreateUpdateInstanceSchedulerCommand startDate(OffsetDateTime startDate) {
    this.startDate = startDate;
    return this;
  }

   /**
   * Start date
   * @return startDate
  **/
  @ApiModelProperty(required = true, value = "Start date")
  public OffsetDateTime getStartDate() {
    return startDate;
  }

  public void setStartDate(OffsetDateTime startDate) {
    this.startDate = startDate;
  }

    public CreateUpdateInstanceSchedulerCommand timeZoneName(String timeZoneName) {
        this.timeZoneName = timeZoneName;
        return this;
    }

    /**
     * Timezone name
     *
     * @return timeZoneName
     **/
    @ApiModelProperty(required = true, value = "Timezone name")
    public String getTimeZoneName() {
        return timeZoneName;
    }

    public void setTimeZoneName(String timeZoneName) {
        this.timeZoneName = timeZoneName;
    }

  public CreateUpdateInstanceSchedulerCommand cycleTypeId(Integer cycleTypeId) {
    this.cycleTypeId = cycleTypeId;
    return this;
  }

   /**
   * Cycle type id
   * @return cycleTypeId
  **/
  @ApiModelProperty(value = "Cycle type id")
  public Integer getCycleTypeId() {
    return cycleTypeId;
  }

  public void setCycleTypeId(Integer cycleTypeId) {
    this.cycleTypeId = cycleTypeId;
  }

  public CreateUpdateInstanceSchedulerCommand cycleNumber(Integer cycleNumber) {
    this.cycleNumber = cycleNumber;
    return this;
  }

   /**
   * Cycle number beetwen scheduler launch
   * minimum: 1
   * maximum: 32767
   * @return cycleNumber
  **/
  @ApiModelProperty(value = "Cycle number beetwen scheduler launch")
  public Integer getCycleNumber() {
    return cycleNumber;
  }

  public void setCycleNumber(Integer cycleNumber) {
    this.cycleNumber = cycleNumber;
  }

  public CreateUpdateInstanceSchedulerCommand actionTypeId(Integer actionTypeId) {
    this.actionTypeId = actionTypeId;
    return this;
  }

   /**
   * Action type
   * @return actionTypeId
  **/
  @ApiModelProperty(required = true, value = "Action type")
  public Integer getActionTypeId() {
    return actionTypeId;
  }

  public void setActionTypeId(Integer actionTypeId) {
    this.actionTypeId = actionTypeId;
  }

  public CreateUpdateInstanceSchedulerCommand newInstanceTypeId(Integer newInstanceTypeId) {
    this.newInstanceTypeId = newInstanceTypeId;
    return this;
  }

   /**
   * New instance type. In case of \&quot;Instance type change\&quot; action type.
   * @return newInstanceTypeId
  **/
  @ApiModelProperty(value = "New instance type. In case of \"Instance type change\" action type.")
  public Integer getNewInstanceTypeId() {
    return newInstanceTypeId;
  }

  public void setNewInstanceTypeId(Integer newInstanceTypeId) {
    this.newInstanceTypeId = newInstanceTypeId;
  }

  public CreateUpdateInstanceSchedulerCommand snapshotName(String snapshotName) {
    this.snapshotName = snapshotName;
    return this;
  }

   /**
   * Snapshot name. In case of \&quot;Create snapshot\&quot; action type.
   * @return snapshotName
  **/
  @ApiModelProperty(value = "Snapshot name. In case of \"Create snapshot\" action type.")
  public String getSnapshotName() {
    return snapshotName;
  }

  public void setSnapshotName(String snapshotName) {
    this.snapshotName = snapshotName;
  }

  public CreateUpdateInstanceSchedulerCommand snapshotDescription(String snapshotDescription) {
    this.snapshotDescription = snapshotDescription;
    return this;
  }

   /**
   * Snapshot description. In case of \&quot;Create snapshot\&quot; action type.
   * @return snapshotDescription
  **/
  @ApiModelProperty(value = "Snapshot description. In case of \"Create snapshot\" action type.")
  public String getSnapshotDescription() {
    return snapshotDescription;
  }

  public void setSnapshotDescription(String snapshotDescription) {
    this.snapshotDescription = snapshotDescription;
  }

  public CreateUpdateInstanceSchedulerCommand snapshotId(Integer snapshotId) {
    this.snapshotId = snapshotId;
    return this;
  }

   /**
   * Snashot. In case of \&quot;Delete snapshot\&quot; action type.
   * @return snapshotId
  **/
  @ApiModelProperty(value = "Snashot. In case of \"Delete snapshot\" action type.")
  public Integer getSnapshotId() {
    return snapshotId;
  }

  public void setSnapshotId(Integer snapshotId) {
    this.snapshotId = snapshotId;
  }

  public CreateUpdateInstanceSchedulerCommand cloneName(String cloneName) {
    this.cloneName = cloneName;
    return this;
  }

   /**
   * Clone name. In case of \&quot;Clone machine\&quot; action type.
   * @return cloneName
  **/
  @ApiModelProperty(value = "Clone name. In case of \"Clone machine\" action type.")
  public String getCloneName() {
    return cloneName;
  }

  public void setCloneName(String cloneName) {
    this.cloneName = cloneName;
  }

  public CreateUpdateInstanceSchedulerCommand storagePath(String storagePath) {
    this.storagePath = storagePath;
    return this;
  }

   /**
   * Storage path. In case of \&quot;Create backup\&quot; action type.
   * @return storagePath
  **/
  @ApiModelProperty(value = "Storage path. In case of \"Create backup\" action type.")
  public String getStoragePath() {
    return storagePath;
  }

  public void setStoragePath(String storagePath) {
    this.storagePath = storagePath;
  }

  public CreateUpdateInstanceSchedulerCommand storageProjectId(String storageProjectId) {
    this.storageProjectId = storageProjectId;
    return this;
  }

   /**
   * Storage project id. In case of \&quot;Create backup\&quot; action type.
   * @return storageProjectId
  **/
  @ApiModelProperty(value = "Storage project id. In case of \"Create backup\" action type.")
  public String getStorageProjectId() {
    return storageProjectId;
  }

  public void setStorageProjectId(String storageProjectId) {
    this.storageProjectId = storageProjectId;
  }

  public CreateUpdateInstanceSchedulerCommand isBackupsDaysLimit(Boolean isBackupsDaysLimit) {
    this.isBackupsDaysLimit = isBackupsDaysLimit;
    return this;
  }

   /**
   * Is backups days limit set. In case of \&quot;Create backup\&quot; action type.
   * @return isBackupsDaysLimit
  **/
  @ApiModelProperty(value = "Is backups days limit set. In case of \"Create backup\" action type.")
  public Boolean isIsBackupsDaysLimit() {
    return isBackupsDaysLimit;
  }

  public void setIsBackupsDaysLimit(Boolean isBackupsDaysLimit) {
    this.isBackupsDaysLimit = isBackupsDaysLimit;
  }

  public CreateUpdateInstanceSchedulerCommand backupsDaysLimit(Integer backupsDaysLimit) {
    this.backupsDaysLimit = backupsDaysLimit;
    return this;
  }

   /**
   * Backups days limit. In case of \&quot;Create backup\&quot; action type.
   * @return backupsDaysLimit
  **/
  @ApiModelProperty(value = "Backups days limit. In case of \"Create backup\" action type.")
  public Integer getBackupsDaysLimit() {
    return backupsDaysLimit;
  }

  public void setBackupsDaysLimit(Integer backupsDaysLimit) {
    this.backupsDaysLimit = backupsDaysLimit;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateUpdateInstanceSchedulerCommand createUpdateInstanceSchedulerCommand = (CreateUpdateInstanceSchedulerCommand) o;
    return Objects.equals(this.name, createUpdateInstanceSchedulerCommand.name) &&
        Objects.equals(this.typeId, createUpdateInstanceSchedulerCommand.typeId) &&
        Objects.equals(this.startDate, createUpdateInstanceSchedulerCommand.startDate) &&
            Objects.equals(this.timeZoneName, createUpdateInstanceSchedulerCommand.timeZoneName) &&
        Objects.equals(this.cycleTypeId, createUpdateInstanceSchedulerCommand.cycleTypeId) &&
        Objects.equals(this.cycleNumber, createUpdateInstanceSchedulerCommand.cycleNumber) &&
        Objects.equals(this.actionTypeId, createUpdateInstanceSchedulerCommand.actionTypeId) &&
        Objects.equals(this.newInstanceTypeId, createUpdateInstanceSchedulerCommand.newInstanceTypeId) &&
        Objects.equals(this.snapshotName, createUpdateInstanceSchedulerCommand.snapshotName) &&
        Objects.equals(this.snapshotDescription, createUpdateInstanceSchedulerCommand.snapshotDescription) &&
        Objects.equals(this.snapshotId, createUpdateInstanceSchedulerCommand.snapshotId) &&
        Objects.equals(this.cloneName, createUpdateInstanceSchedulerCommand.cloneName) &&
        Objects.equals(this.storagePath, createUpdateInstanceSchedulerCommand.storagePath) &&
        Objects.equals(this.storageProjectId, createUpdateInstanceSchedulerCommand.storageProjectId) &&
        Objects.equals(this.isBackupsDaysLimit, createUpdateInstanceSchedulerCommand.isBackupsDaysLimit) &&
        Objects.equals(this.backupsDaysLimit, createUpdateInstanceSchedulerCommand.backupsDaysLimit);
  }

  @Override
  public int hashCode() {
      return Objects.hash(name, typeId, startDate, timeZoneName, cycleTypeId, cycleNumber, actionTypeId, newInstanceTypeId, snapshotName, snapshotDescription, snapshotId, cloneName, storagePath, storageProjectId, isBackupsDaysLimit, backupsDaysLimit);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateUpdateInstanceSchedulerCommand {\n");

    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    typeId: ").append(toIndentedString(typeId)).append("\n");
    sb.append("    startDate: ").append(toIndentedString(startDate)).append("\n");
      sb.append("    timeZoneName: ").append(toIndentedString(timeZoneName)).append("\n");
    sb.append("    cycleTypeId: ").append(toIndentedString(cycleTypeId)).append("\n");
    sb.append("    cycleNumber: ").append(toIndentedString(cycleNumber)).append("\n");
    sb.append("    actionTypeId: ").append(toIndentedString(actionTypeId)).append("\n");
    sb.append("    newInstanceTypeId: ").append(toIndentedString(newInstanceTypeId)).append("\n");
    sb.append("    snapshotName: ").append(toIndentedString(snapshotName)).append("\n");
    sb.append("    snapshotDescription: ").append(toIndentedString(snapshotDescription)).append("\n");
    sb.append("    snapshotId: ").append(toIndentedString(snapshotId)).append("\n");
    sb.append("    cloneName: ").append(toIndentedString(cloneName)).append("\n");
    sb.append("    storagePath: ").append(toIndentedString(storagePath)).append("\n");
    sb.append("    storageProjectId: ").append(toIndentedString(storageProjectId)).append("\n");
    sb.append("    isBackupsDaysLimit: ").append(toIndentedString(isBackupsDaysLimit)).append("\n");
    sb.append("    backupsDaysLimit: ").append(toIndentedString(backupsDaysLimit)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

