/*
 * Oktawave API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.oktawave.api.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * Create export command
 */
@ApiModel(description = "Create export command")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-02-03T15:23:33.358+01:00")
public class CreateExportCommand {
  @SerializedName("Name")
  private String name = null;

  @SerializedName("OcsLocation")
  private String ocsLocation = null;

  @SerializedName("OcsProjectId")
  private String ocsProjectId = null;

  public CreateExportCommand name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name
   * @return name
  **/
  @ApiModelProperty(required = true, value = "Name")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public CreateExportCommand ocsLocation(String ocsLocation) {
    this.ocsLocation = ocsLocation;
    return this;
  }

   /**
   * OCS location
   * @return ocsLocation
  **/
  @ApiModelProperty(required = true, value = "OCS location")
  public String getOcsLocation() {
    return ocsLocation;
  }

  public void setOcsLocation(String ocsLocation) {
    this.ocsLocation = ocsLocation;
  }

  public CreateExportCommand ocsProjectId(String ocsProjectId) {
    this.ocsProjectId = ocsProjectId;
    return this;
  }

   /**
   * OCS Project Id
   * @return ocsProjectId
  **/
  @ApiModelProperty(required = true, value = "OCS Project Id")
  public String getOcsProjectId() {
    return ocsProjectId;
  }

  public void setOcsProjectId(String ocsProjectId) {
    this.ocsProjectId = ocsProjectId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateExportCommand createExportCommand = (CreateExportCommand) o;
    return Objects.equals(this.name, createExportCommand.name) &&
        Objects.equals(this.ocsLocation, createExportCommand.ocsLocation) &&
        Objects.equals(this.ocsProjectId, createExportCommand.ocsProjectId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, ocsLocation, ocsProjectId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateExportCommand {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    ocsLocation: ").append(toIndentedString(ocsLocation)).append("\n");
    sb.append("    ocsProjectId: ").append(toIndentedString(ocsProjectId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

