/*
 * Oktawave API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.oktawave.api.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * Create/update VNC connection command
 */
@ApiModel(description = "Create/update VNC connection command")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-04-25T12:05:03.973+02:00")
public class CreateUpdateVncConnectionCommand {
  @SerializedName("SourceIp")
  private String sourceIp = null;

  @SerializedName("TimeoutInMinutes")
  private Integer timeoutInMinutes = null;

  public CreateUpdateVncConnectionCommand sourceIp(String sourceIp) {
    this.sourceIp = sourceIp;
    return this;
  }

   /**
   * Source ip - only connections from this source ip will be accepted
   * @return sourceIp
  **/
  @ApiModelProperty(value = "Source ip - only connections from this source ip will be accepted")
  public String getSourceIp() {
    return sourceIp;
  }

  public void setSourceIp(String sourceIp) {
    this.sourceIp = sourceIp;
  }

  public CreateUpdateVncConnectionCommand timeoutInMinutes(Integer timeoutInMinutes) {
    this.timeoutInMinutes = timeoutInMinutes;
    return this;
  }

   /**
   * Connection will be closed after that period
   * minimum: 30
   * maximum: 360
   * @return timeoutInMinutes
  **/
  @ApiModelProperty(required = true, value = "Connection will be closed after that period")
  public Integer getTimeoutInMinutes() {
    return timeoutInMinutes;
  }

  public void setTimeoutInMinutes(Integer timeoutInMinutes) {
    this.timeoutInMinutes = timeoutInMinutes;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateUpdateVncConnectionCommand createUpdateVncConnectionCommand = (CreateUpdateVncConnectionCommand) o;
    return Objects.equals(this.sourceIp, createUpdateVncConnectionCommand.sourceIp) &&
        Objects.equals(this.timeoutInMinutes, createUpdateVncConnectionCommand.timeoutInMinutes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sourceIp, timeoutInMinutes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateUpdateVncConnectionCommand {\n");
    
    sb.append("    sourceIp: ").append(toIndentedString(sourceIp)).append("\n");
    sb.append("    timeoutInMinutes: ").append(toIndentedString(timeoutInMinutes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

