/*
 * Oktawave API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.oktawave.api.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.threeten.bp.OffsetDateTime;

import java.io.IOException;
import java.util.Objects;

/**
 * Search params for instance events
 */
@ApiModel(description = "Search params for instance events")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-02-03T15:23:33.358+01:00")
public class EventsSearchParams {
  @SerializedName("UserId")
  private Integer userId = null;

  @SerializedName("DateFrom")
  private OffsetDateTime dateFrom = null;

  @SerializedName("DateTo")
  private OffsetDateTime dateTo = null;

  @SerializedName("OperationTypeId")
  private Integer operationTypeId = null;

  @SerializedName("PageSize")
  private Integer pageSize = null;

  @SerializedName("PageNumber")
  private Integer pageNumber = null;

  @SerializedName("OrderBy")
  private String orderBy = null;

  @SerializedName("SortExpression")
  private String sortExpression = null;

  /**
   * Sort direction
   */
  @JsonAdapter(SortDirectionEnum.Adapter.class)
  public enum SortDirectionEnum {
    DESCENDING("Descending"),
    
    ASCENDING("Ascending");

    private String value;

    SortDirectionEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static SortDirectionEnum fromValue(String text) {
      for (SortDirectionEnum b : SortDirectionEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<SortDirectionEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final SortDirectionEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public SortDirectionEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return SortDirectionEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("SortDirection")
  private SortDirectionEnum sortDirection = null;

  public EventsSearchParams userId(Integer userId) {
    this.userId = userId;
    return this;
  }

   /**
   * User id
   * @return userId
  **/
  @ApiModelProperty(value = "User id")
  public Integer getUserId() {
    return userId;
  }

  public void setUserId(Integer userId) {
    this.userId = userId;
  }

  public EventsSearchParams dateFrom(OffsetDateTime dateFrom) {
    this.dateFrom = dateFrom;
    return this;
  }

   /**
   * Date from
   * @return dateFrom
  **/
  @ApiModelProperty(value = "Date from")
  public OffsetDateTime getDateFrom() {
    return dateFrom;
  }

  public void setDateFrom(OffsetDateTime dateFrom) {
    this.dateFrom = dateFrom;
  }

  public EventsSearchParams dateTo(OffsetDateTime dateTo) {
    this.dateTo = dateTo;
    return this;
  }

   /**
   * Date to
   * @return dateTo
  **/
  @ApiModelProperty(value = "Date to")
  public OffsetDateTime getDateTo() {
    return dateTo;
  }

  public void setDateTo(OffsetDateTime dateTo) {
    this.dateTo = dateTo;
  }

  public EventsSearchParams operationTypeId(Integer operationTypeId) {
    this.operationTypeId = operationTypeId;
    return this;
  }

   /**
   * Operation type id
   * @return operationTypeId
  **/
  @ApiModelProperty(value = "Operation type id")
  public Integer getOperationTypeId() {
    return operationTypeId;
  }

  public void setOperationTypeId(Integer operationTypeId) {
    this.operationTypeId = operationTypeId;
  }

  public EventsSearchParams pageSize(Integer pageSize) {
    this.pageSize = pageSize;
    return this;
  }

   /**
   * Page size
   * @return pageSize
  **/
  @ApiModelProperty(value = "Page size")
  public Integer getPageSize() {
    return pageSize;
  }

  public void setPageSize(Integer pageSize) {
    this.pageSize = pageSize;
  }

  public EventsSearchParams pageNumber(Integer pageNumber) {
    this.pageNumber = pageNumber;
    return this;
  }

   /**
   * Page number
   * @return pageNumber
  **/
  @ApiModelProperty(value = "Page number")
  public Integer getPageNumber() {
    return pageNumber;
  }

  public void setPageNumber(Integer pageNumber) {
    this.pageNumber = pageNumber;
  }

  public EventsSearchParams orderBy(String orderBy) {
    this.orderBy = orderBy;
    return this;
  }

   /**
   * Order by
   * @return orderBy
  **/
  @ApiModelProperty(value = "Order by")
  public String getOrderBy() {
    return orderBy;
  }

  public void setOrderBy(String orderBy) {
    this.orderBy = orderBy;
  }

   /**
   * Sort expression
   * @return sortExpression
  **/
  @ApiModelProperty(value = "Sort expression")
  public String getSortExpression() {
    return sortExpression;
  }

   /**
   * Sort direction
   * @return sortDirection
  **/
  @ApiModelProperty(value = "Sort direction")
  public SortDirectionEnum getSortDirection() {
    return sortDirection;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EventsSearchParams eventsSearchParams = (EventsSearchParams) o;
    return Objects.equals(this.userId, eventsSearchParams.userId) &&
        Objects.equals(this.dateFrom, eventsSearchParams.dateFrom) &&
        Objects.equals(this.dateTo, eventsSearchParams.dateTo) &&
        Objects.equals(this.operationTypeId, eventsSearchParams.operationTypeId) &&
        Objects.equals(this.pageSize, eventsSearchParams.pageSize) &&
        Objects.equals(this.pageNumber, eventsSearchParams.pageNumber) &&
        Objects.equals(this.orderBy, eventsSearchParams.orderBy) &&
        Objects.equals(this.sortExpression, eventsSearchParams.sortExpression) &&
        Objects.equals(this.sortDirection, eventsSearchParams.sortDirection);
  }

  @Override
  public int hashCode() {
    return Objects.hash(userId, dateFrom, dateTo, operationTypeId, pageSize, pageNumber, orderBy, sortExpression, sortDirection);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EventsSearchParams {\n");

      sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    dateFrom: ").append(toIndentedString(dateFrom)).append("\n");
    sb.append("    dateTo: ").append(toIndentedString(dateTo)).append("\n");
    sb.append("    operationTypeId: ").append(toIndentedString(operationTypeId)).append("\n");
    sb.append("    pageSize: ").append(toIndentedString(pageSize)).append("\n");
    sb.append("    pageNumber: ").append(toIndentedString(pageNumber)).append("\n");
    sb.append("    orderBy: ").append(toIndentedString(orderBy)).append("\n");
    sb.append("    sortExpression: ").append(toIndentedString(sortExpression)).append("\n");
    sb.append("    sortDirection: ").append(toIndentedString(sortDirection)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

