/*
 * Oktawave API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.oktawave.api.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.threeten.bp.OffsetDateTime;

import java.util.Objects;

/**
 * Event that have occurred on instance
 */
@ApiModel(description = "Event that have occurred on instance")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-02-03T15:23:33.358+01:00")
public class InstanceEvent {
  @SerializedName("Id")
  private Long id = null;

  @SerializedName("Date")
  private OffsetDateTime date = null;

  @SerializedName("Instance")
  private NamedResource instance = null;

  @SerializedName("User")
  private UserResource user = null;

  @SerializedName("OperationType")
  private DictionaryItem operationType = null;

  @SerializedName("OperationStatus")
  private DictionaryItem operationStatus = null;

  @SerializedName("Message")
  private String message = null;

  public InstanceEvent id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Id
   * @return id
  **/
  @ApiModelProperty(value = "Id")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public InstanceEvent date(OffsetDateTime date) {
    this.date = date;
    return this;
  }

   /**
   * Date
   * @return date
  **/
  @ApiModelProperty(value = "Date")
  public OffsetDateTime getDate() {
    return date;
  }

  public void setDate(OffsetDateTime date) {
    this.date = date;
  }

  public InstanceEvent instance(NamedResource instance) {
    this.instance = instance;
    return this;
  }

   /**
   * Instance
   * @return instance
  **/
  @ApiModelProperty(value = "Instance")
  public NamedResource getInstance() {
    return instance;
  }

  public void setInstance(NamedResource instance) {
    this.instance = instance;
  }

  public InstanceEvent user(UserResource user) {
    this.user = user;
    return this;
  }

   /**
   * User who performed the operation
   * @return user
  **/
  @ApiModelProperty(value = "User who performed the operation")
  public UserResource getUser() {
    return user;
  }

  public void setUser(UserResource user) {
    this.user = user;
  }

  public InstanceEvent operationType(DictionaryItem operationType) {
    this.operationType = operationType;
    return this;
  }

   /**
   * Operation type
   * @return operationType
  **/
  @ApiModelProperty(value = "Operation type")
  public DictionaryItem getOperationType() {
    return operationType;
  }

  public void setOperationType(DictionaryItem operationType) {
    this.operationType = operationType;
  }

  public InstanceEvent operationStatus(DictionaryItem operationStatus) {
    this.operationStatus = operationStatus;
    return this;
  }

   /**
   * Operation status
   * @return operationStatus
  **/
  @ApiModelProperty(value = "Operation status")
  public DictionaryItem getOperationStatus() {
    return operationStatus;
  }

  public void setOperationStatus(DictionaryItem operationStatus) {
    this.operationStatus = operationStatus;
  }

  public InstanceEvent message(String message) {
    this.message = message;
    return this;
  }

   /**
   * Message
   * @return message
  **/
  @ApiModelProperty(value = "Message")
  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InstanceEvent instanceEvent = (InstanceEvent) o;
    return Objects.equals(this.id, instanceEvent.id) &&
        Objects.equals(this.date, instanceEvent.date) &&
        Objects.equals(this.instance, instanceEvent.instance) &&
        Objects.equals(this.user, instanceEvent.user) &&
        Objects.equals(this.operationType, instanceEvent.operationType) &&
        Objects.equals(this.operationStatus, instanceEvent.operationStatus) &&
        Objects.equals(this.message, instanceEvent.message);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, date, instance, user, operationType, operationStatus, message);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InstanceEvent {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    instance: ").append(toIndentedString(instance)).append("\n");
    sb.append("    user: ").append(toIndentedString(user)).append("\n");
    sb.append("    operationType: ").append(toIndentedString(operationType)).append("\n");
    sb.append("    operationStatus: ").append(toIndentedString(operationStatus)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

