/*
 * Oktawave API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.oktawave.api.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.io.IOException;
import java.util.Objects;

/**
 * Search params for instances
 */
@ApiModel(description = "Search params for instances")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-02-03T15:23:33.358+01:00")
public class InstancesSearchParams {
  @SerializedName("TemplateTypeId")
  private Integer templateTypeId = null;

  @SerializedName("IsTurnedOn")
  private Boolean isTurnedOn = null;

  @SerializedName("SubregionId")
  private Integer subregionId = null;

  @SerializedName("TypeId")
  private Integer typeId = null;

  @SerializedName("Query")
  private String query = null;

  @SerializedName("PageSize")
  private Integer pageSize = null;

  @SerializedName("PageNumber")
  private Integer pageNumber = null;

  @SerializedName("OrderBy")
  private String orderBy = null;

  @SerializedName("SortExpression")
  private String sortExpression = null;

  /**
   * Sort direction
   */
  @JsonAdapter(SortDirectionEnum.Adapter.class)
  public enum SortDirectionEnum {
    DESCENDING("Descending"),
    
    ASCENDING("Ascending");

    private String value;

    SortDirectionEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static SortDirectionEnum fromValue(String text) {
      for (SortDirectionEnum b : SortDirectionEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<SortDirectionEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final SortDirectionEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public SortDirectionEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return SortDirectionEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("SortDirection")
  private SortDirectionEnum sortDirection = null;

  public InstancesSearchParams templateTypeId(Integer templateTypeId) {
    this.templateTypeId = templateTypeId;
    return this;
  }

   /**
   * Template type id eg marketplace, oci instance
   * @return templateTypeId
  **/
  @ApiModelProperty(value = "Template type id eg marketplace, oci instance")
  public Integer getTemplateTypeId() {
    return templateTypeId;
  }

  public void setTemplateTypeId(Integer templateTypeId) {
    this.templateTypeId = templateTypeId;
  }

  public InstancesSearchParams isTurnedOn(Boolean isTurnedOn) {
    this.isTurnedOn = isTurnedOn;
    return this;
  }

   /**
   * Indicates wether an instance is turned on
   * @return isTurnedOn
  **/
  @ApiModelProperty(value = "Indicates wether an instance is turned on")
  public Boolean isIsTurnedOn() {
    return isTurnedOn;
  }

  public void setIsTurnedOn(Boolean isTurnedOn) {
    this.isTurnedOn = isTurnedOn;
  }

  public InstancesSearchParams subregionId(Integer subregionId) {
    this.subregionId = subregionId;
    return this;
  }

   /**
   * Subregion Id
   * @return subregionId
  **/
  @ApiModelProperty(value = "Subregion Id")
  public Integer getSubregionId() {
    return subregionId;
  }

  public void setSubregionId(Integer subregionId) {
    this.subregionId = subregionId;
  }

  public InstancesSearchParams typeId(Integer typeId) {
    this.typeId = typeId;
    return this;
  }

   /**
   * Type Id
   * @return typeId
  **/
  @ApiModelProperty(value = "Type Id")
  public Integer getTypeId() {
    return typeId;
  }

  public void setTypeId(Integer typeId) {
    this.typeId = typeId;
  }

  public InstancesSearchParams query(String query) {
    this.query = query;
    return this;
  }

   /**
   * Query
   * @return query
  **/
  @ApiModelProperty(value = "Query")
  public String getQuery() {
    return query;
  }

  public void setQuery(String query) {
    this.query = query;
  }

  public InstancesSearchParams pageSize(Integer pageSize) {
    this.pageSize = pageSize;
    return this;
  }

   /**
   * Page size
   * @return pageSize
  **/
  @ApiModelProperty(value = "Page size")
  public Integer getPageSize() {
    return pageSize;
  }

  public void setPageSize(Integer pageSize) {
    this.pageSize = pageSize;
  }

  public InstancesSearchParams pageNumber(Integer pageNumber) {
    this.pageNumber = pageNumber;
    return this;
  }

   /**
   * Page number
   * @return pageNumber
  **/
  @ApiModelProperty(value = "Page number")
  public Integer getPageNumber() {
    return pageNumber;
  }

  public void setPageNumber(Integer pageNumber) {
    this.pageNumber = pageNumber;
  }

  public InstancesSearchParams orderBy(String orderBy) {
    this.orderBy = orderBy;
    return this;
  }

   /**
   * Order by
   * @return orderBy
  **/
  @ApiModelProperty(value = "Order by")
  public String getOrderBy() {
    return orderBy;
  }

  public void setOrderBy(String orderBy) {
    this.orderBy = orderBy;
  }

   /**
   * Sort expression
   * @return sortExpression
  **/
  @ApiModelProperty(value = "Sort expression")
  public String getSortExpression() {
    return sortExpression;
  }

   /**
   * Sort direction
   * @return sortDirection
  **/
  @ApiModelProperty(value = "Sort direction")
  public SortDirectionEnum getSortDirection() {
    return sortDirection;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InstancesSearchParams instancesSearchParams = (InstancesSearchParams) o;
    return Objects.equals(this.templateTypeId, instancesSearchParams.templateTypeId) &&
        Objects.equals(this.isTurnedOn, instancesSearchParams.isTurnedOn) &&
        Objects.equals(this.subregionId, instancesSearchParams.subregionId) &&
        Objects.equals(this.typeId, instancesSearchParams.typeId) &&
        Objects.equals(this.query, instancesSearchParams.query) &&
        Objects.equals(this.pageSize, instancesSearchParams.pageSize) &&
        Objects.equals(this.pageNumber, instancesSearchParams.pageNumber) &&
        Objects.equals(this.orderBy, instancesSearchParams.orderBy) &&
        Objects.equals(this.sortExpression, instancesSearchParams.sortExpression) &&
        Objects.equals(this.sortDirection, instancesSearchParams.sortDirection);
  }

  @Override
  public int hashCode() {
    return Objects.hash(templateTypeId, isTurnedOn, subregionId, typeId, query, pageSize, pageNumber, orderBy, sortExpression, sortDirection);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InstancesSearchParams {\n");

      sb.append("    templateTypeId: ").append(toIndentedString(templateTypeId)).append("\n");
    sb.append("    isTurnedOn: ").append(toIndentedString(isTurnedOn)).append("\n");
    sb.append("    subregionId: ").append(toIndentedString(subregionId)).append("\n");
    sb.append("    typeId: ").append(toIndentedString(typeId)).append("\n");
    sb.append("    query: ").append(toIndentedString(query)).append("\n");
    sb.append("    pageSize: ").append(toIndentedString(pageSize)).append("\n");
    sb.append("    pageNumber: ").append(toIndentedString(pageNumber)).append("\n");
    sb.append("    orderBy: ").append(toIndentedString(orderBy)).append("\n");
    sb.append("    sortExpression: ").append(toIndentedString(sortExpression)).append("\n");
    sb.append("    sortDirection: ").append(toIndentedString(sortDirection)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

