/*
 * Oktawave API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.oktawave.api.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * Load balancer service
 */
@ApiModel(description = "Load balancer service")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-02-03T15:23:33.358+01:00")
public class LoadBalancerService {
  @SerializedName("Instance")
  private NamedResource instance = null;

  @SerializedName("InstanceState")
  private DictionaryItem instanceState = null;

  @SerializedName("IpAddress")
  private String ipAddress = null;

  @SerializedName("Port")
  private Integer port = null;

  @SerializedName("RequestRate")
  private Long requestRate = null;

  @SerializedName("ResponseRate")
  private Long responseRate = null;

  @SerializedName("RequestRateBytes")
  private Long requestRateBytes = null;

  @SerializedName("ResponseRateBytes")
  private Long responseRateBytes = null;

  @SerializedName("CurrentClientConnections")
  private Long currentClientConnections = null;

  @SerializedName("Status")
  private DictionaryItem status = null;

  public LoadBalancerService instance(NamedResource instance) {
    this.instance = instance;
    return this;
  }

   /**
   * Instance
   * @return instance
  **/
  @ApiModelProperty(value = "Instance")
  public NamedResource getInstance() {
    return instance;
  }

  public void setInstance(NamedResource instance) {
    this.instance = instance;
  }

  public LoadBalancerService instanceState(DictionaryItem instanceState) {
    this.instanceState = instanceState;
    return this;
  }

   /**
   * Instance state
   * @return instanceState
  **/
  @ApiModelProperty(value = "Instance state")
  public DictionaryItem getInstanceState() {
    return instanceState;
  }

  public void setInstanceState(DictionaryItem instanceState) {
    this.instanceState = instanceState;
  }

  public LoadBalancerService ipAddress(String ipAddress) {
    this.ipAddress = ipAddress;
    return this;
  }

   /**
   * Ip address
   * @return ipAddress
  **/
  @ApiModelProperty(value = "Ip address")
  public String getIpAddress() {
    return ipAddress;
  }

  public void setIpAddress(String ipAddress) {
    this.ipAddress = ipAddress;
  }

  public LoadBalancerService port(Integer port) {
    this.port = port;
    return this;
  }

   /**
   * Port
   * @return port
  **/
  @ApiModelProperty(value = "Port")
  public Integer getPort() {
    return port;
  }

  public void setPort(Integer port) {
    this.port = port;
  }

  public LoadBalancerService requestRate(Long requestRate) {
    this.requestRate = requestRate;
    return this;
  }

   /**
   * Request rate
   * @return requestRate
  **/
  @ApiModelProperty(value = "Request rate")
  public Long getRequestRate() {
    return requestRate;
  }

  public void setRequestRate(Long requestRate) {
    this.requestRate = requestRate;
  }

  public LoadBalancerService responseRate(Long responseRate) {
    this.responseRate = responseRate;
    return this;
  }

   /**
   * Response rate
   * @return responseRate
  **/
  @ApiModelProperty(value = "Response rate")
  public Long getResponseRate() {
    return responseRate;
  }

  public void setResponseRate(Long responseRate) {
    this.responseRate = responseRate;
  }

  public LoadBalancerService requestRateBytes(Long requestRateBytes) {
    this.requestRateBytes = requestRateBytes;
    return this;
  }

   /**
   * Request rate in bytes
   * @return requestRateBytes
  **/
  @ApiModelProperty(value = "Request rate in bytes")
  public Long getRequestRateBytes() {
    return requestRateBytes;
  }

  public void setRequestRateBytes(Long requestRateBytes) {
    this.requestRateBytes = requestRateBytes;
  }

  public LoadBalancerService responseRateBytes(Long responseRateBytes) {
    this.responseRateBytes = responseRateBytes;
    return this;
  }

   /**
   * Response rate in bytes
   * @return responseRateBytes
  **/
  @ApiModelProperty(value = "Response rate in bytes")
  public Long getResponseRateBytes() {
    return responseRateBytes;
  }

  public void setResponseRateBytes(Long responseRateBytes) {
    this.responseRateBytes = responseRateBytes;
  }

  public LoadBalancerService currentClientConnections(Long currentClientConnections) {
    this.currentClientConnections = currentClientConnections;
    return this;
  }

   /**
   * Current client connections
   * @return currentClientConnections
  **/
  @ApiModelProperty(value = "Current client connections")
  public Long getCurrentClientConnections() {
    return currentClientConnections;
  }

  public void setCurrentClientConnections(Long currentClientConnections) {
    this.currentClientConnections = currentClientConnections;
  }

  public LoadBalancerService status(DictionaryItem status) {
    this.status = status;
    return this;
  }

   /**
   * Status
   * @return status
  **/
  @ApiModelProperty(value = "Status")
  public DictionaryItem getStatus() {
    return status;
  }

  public void setStatus(DictionaryItem status) {
    this.status = status;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LoadBalancerService loadBalancerService = (LoadBalancerService) o;
    return Objects.equals(this.instance, loadBalancerService.instance) &&
        Objects.equals(this.instanceState, loadBalancerService.instanceState) &&
        Objects.equals(this.ipAddress, loadBalancerService.ipAddress) &&
        Objects.equals(this.port, loadBalancerService.port) &&
        Objects.equals(this.requestRate, loadBalancerService.requestRate) &&
        Objects.equals(this.responseRate, loadBalancerService.responseRate) &&
        Objects.equals(this.requestRateBytes, loadBalancerService.requestRateBytes) &&
        Objects.equals(this.responseRateBytes, loadBalancerService.responseRateBytes) &&
        Objects.equals(this.currentClientConnections, loadBalancerService.currentClientConnections) &&
        Objects.equals(this.status, loadBalancerService.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(instance, instanceState, ipAddress, port, requestRate, responseRate, requestRateBytes, responseRateBytes, currentClientConnections, status);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LoadBalancerService {\n");

      sb.append("    instance: ").append(toIndentedString(instance)).append("\n");
    sb.append("    instanceState: ").append(toIndentedString(instanceState)).append("\n");
    sb.append("    ipAddress: ").append(toIndentedString(ipAddress)).append("\n");
    sb.append("    port: ").append(toIndentedString(port)).append("\n");
    sb.append("    requestRate: ").append(toIndentedString(requestRate)).append("\n");
    sb.append("    responseRate: ").append(toIndentedString(responseRate)).append("\n");
    sb.append("    requestRateBytes: ").append(toIndentedString(requestRateBytes)).append("\n");
    sb.append("    responseRateBytes: ").append(toIndentedString(responseRateBytes)).append("\n");
    sb.append("    currentClientConnections: ").append(toIndentedString(currentClientConnections)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

