/*
 * Oktawave API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.oktawave.api.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * NullableTime
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-02-03T15:23:33.358+01:00")
public class NullableTime {
  @SerializedName("Hours")
  private Integer hours = null;

  @SerializedName("Minutes")
  private Integer minutes = null;

   /**
   * Hours
   * @return hours
  **/
  @ApiModelProperty(value = "Hours")
  public Integer getHours() {
    return hours;
  }

   /**
   * Minutes
   * @return minutes
  **/
  @ApiModelProperty(value = "Minutes")
  public Integer getMinutes() {
    return minutes;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NullableTime nullableTime = (NullableTime) o;
    return Objects.equals(this.hours, nullableTime.hours) &&
        Objects.equals(this.minutes, nullableTime.minutes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(hours, minutes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NullableTime {\n");

      sb.append("    hours: ").append(toIndentedString(hours)).append("\n");
    sb.append("    minutes: ").append(toIndentedString(minutes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

