/*
 * Oktawave API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.oktawave.api.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.threeten.bp.OffsetDateTime;

import java.util.Objects;

/**
 * Private IP address
 */
@ApiModel(description = "Private IP address")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-02-03T15:23:33.358+01:00")
public class PrivateIp {
  @SerializedName("InterfaceId")
  private Integer interfaceId = null;

  @SerializedName("MacAddress")
  private String macAddress = null;

  @SerializedName("Address")
  private String address = null;

  @SerializedName("AddressV6")
  private String addressV6 = null;

  @SerializedName("Instance")
  private BaseResource instance = null;

  @SerializedName("CreationDate")
  private OffsetDateTime creationDate = null;

  public PrivateIp interfaceId(Integer interfaceId) {
    this.interfaceId = interfaceId;
    return this;
  }

   /**
   * Interface id
   * @return interfaceId
  **/
  @ApiModelProperty(value = "Interface id")
  public Integer getInterfaceId() {
    return interfaceId;
  }

  public void setInterfaceId(Integer interfaceId) {
    this.interfaceId = interfaceId;
  }

  public PrivateIp macAddress(String macAddress) {
    this.macAddress = macAddress;
    return this;
  }

   /**
   * The MAC address of the network card associated with that IP address
   * @return macAddress
  **/
  @ApiModelProperty(value = "The MAC address of the network card associated with that IP address")
  public String getMacAddress() {
    return macAddress;
  }

  public void setMacAddress(String macAddress) {
    this.macAddress = macAddress;
  }

  public PrivateIp address(String address) {
    this.address = address;
    return this;
  }

   /**
   * Adres IPv4
   * @return address
  **/
  @ApiModelProperty(value = "Adres IPv4")
  public String getAddress() {
    return address;
  }

  public void setAddress(String address) {
    this.address = address;
  }

  public PrivateIp addressV6(String addressV6) {
    this.addressV6 = addressV6;
    return this;
  }

   /**
   * Adres IPv6
   * @return addressV6
  **/
  @ApiModelProperty(value = "Adres IPv6")
  public String getAddressV6() {
    return addressV6;
  }

  public void setAddressV6(String addressV6) {
    this.addressV6 = addressV6;
  }

  public PrivateIp instance(BaseResource instance) {
    this.instance = instance;
    return this;
  }

   /**
   * Instance
   * @return instance
  **/
  @ApiModelProperty(value = "Instance")
  public BaseResource getInstance() {
    return instance;
  }

  public void setInstance(BaseResource instance) {
    this.instance = instance;
  }

  public PrivateIp creationDate(OffsetDateTime creationDate) {
    this.creationDate = creationDate;
    return this;
  }

   /**
   * Creation date
   * @return creationDate
  **/
  @ApiModelProperty(value = "Creation date")
  public OffsetDateTime getCreationDate() {
    return creationDate;
  }

  public void setCreationDate(OffsetDateTime creationDate) {
    this.creationDate = creationDate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PrivateIp privateIp = (PrivateIp) o;
    return Objects.equals(this.interfaceId, privateIp.interfaceId) &&
        Objects.equals(this.macAddress, privateIp.macAddress) &&
        Objects.equals(this.address, privateIp.address) &&
        Objects.equals(this.addressV6, privateIp.addressV6) &&
        Objects.equals(this.instance, privateIp.instance) &&
        Objects.equals(this.creationDate, privateIp.creationDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(interfaceId, macAddress, address, addressV6, instance, creationDate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PrivateIp {\n");
    
    sb.append("    interfaceId: ").append(toIndentedString(interfaceId)).append("\n");
    sb.append("    macAddress: ").append(toIndentedString(macAddress)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    addressV6: ").append(toIndentedString(addressV6)).append("\n");
    sb.append("    instance: ").append(toIndentedString(instance)).append("\n");
    sb.append("    creationDate: ").append(toIndentedString(creationDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

