/*
 * Oktawave API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.oktawave.api.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * Run import disk command
 */
@ApiModel(description = "Run import disk command")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-02-03T15:23:33.358+01:00")
public class RunImportDiskCommand {
  @SerializedName("ImportDiskId")
  private Integer importDiskId = null;

  @SerializedName("TierId")
  private Integer tierId = null;

  public RunImportDiskCommand importDiskId(Integer importDiskId) {
    this.importDiskId = importDiskId;
    return this;
  }

   /**
   * Id of an imported disk
   * @return importDiskId
  **/
  @ApiModelProperty(required = true, value = "Id of an imported disk")
  public Integer getImportDiskId() {
    return importDiskId;
  }

  public void setImportDiskId(Integer importDiskId) {
    this.importDiskId = importDiskId;
  }

  public RunImportDiskCommand tierId(Integer tierId) {
    this.tierId = tierId;
    return this;
  }

   /**
   * Tier id
   * @return tierId
  **/
  @ApiModelProperty(required = true, value = "Tier id")
  public Integer getTierId() {
    return tierId;
  }

  public void setTierId(Integer tierId) {
    this.tierId = tierId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RunImportDiskCommand runImportDiskCommand = (RunImportDiskCommand) o;
    return Objects.equals(this.importDiskId, runImportDiskCommand.importDiskId) &&
        Objects.equals(this.tierId, runImportDiskCommand.tierId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(importDiskId, tierId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RunImportDiskCommand {\n");

      sb.append("    importDiskId: ").append(toIndentedString(importDiskId)).append("\n");
    sb.append("    tierId: ").append(toIndentedString(tierId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

