/*
 * Oktawave API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.oktawave.api.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Set container autoscaler
 */
@ApiModel(description = "Set container autoscaler")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-02-03T15:23:33.358+01:00")
public class SetGroupAutoscalerCommand {
  @SerializedName("ExpansionTypeId")
  private Integer expansionTypeId = null;

  @SerializedName("MinimumInstanceNumber")
  private Integer minimumInstanceNumber = null;

  @SerializedName("MaximumInstanceNumber")
  private Integer maximumInstanceNumber = null;

  @SerializedName("Instances")
  private List<GroupAutoscalerInstance> instances = new ArrayList<GroupAutoscalerInstance>();

  public SetGroupAutoscalerCommand expansionTypeId(Integer expansionTypeId) {
    this.expansionTypeId = expansionTypeId;
    return this;
  }

   /**
   * Expansion type
   * @return expansionTypeId
  **/
  @ApiModelProperty(required = true, value = "Expansion type")
  public Integer getExpansionTypeId() {
    return expansionTypeId;
  }

  public void setExpansionTypeId(Integer expansionTypeId) {
    this.expansionTypeId = expansionTypeId;
  }

  public SetGroupAutoscalerCommand minimumInstanceNumber(Integer minimumInstanceNumber) {
    this.minimumInstanceNumber = minimumInstanceNumber;
    return this;
  }

   /**
   * Minimum instance number in container
   * minimum: 1
   * maximum: 2147483647
   * @return minimumInstanceNumber
  **/
  @ApiModelProperty(required = true, value = "Minimum instance number in container")
  public Integer getMinimumInstanceNumber() {
    return minimumInstanceNumber;
  }

  public void setMinimumInstanceNumber(Integer minimumInstanceNumber) {
    this.minimumInstanceNumber = minimumInstanceNumber;
  }

  public SetGroupAutoscalerCommand maximumInstanceNumber(Integer maximumInstanceNumber) {
    this.maximumInstanceNumber = maximumInstanceNumber;
    return this;
  }

   /**
   * Minimum instance number in container
   * minimum: 1
   * maximum: 2147483647
   * @return maximumInstanceNumber
  **/
  @ApiModelProperty(required = true, value = "Minimum instance number in container")
  public Integer getMaximumInstanceNumber() {
    return maximumInstanceNumber;
  }

  public void setMaximumInstanceNumber(Integer maximumInstanceNumber) {
    this.maximumInstanceNumber = maximumInstanceNumber;
  }

  public SetGroupAutoscalerCommand instances(List<GroupAutoscalerInstance> instances) {
    this.instances = instances;
    return this;
  }

  public SetGroupAutoscalerCommand addInstancesItem(GroupAutoscalerInstance instancesItem) {
    this.instances.add(instancesItem);
    return this;
  }

   /**
   * Instances to scaling
   * @return instances
  **/
  @ApiModelProperty(required = true, value = "Instances to scaling")
  public List<GroupAutoscalerInstance> getInstances() {
    return instances;
  }

  public void setInstances(List<GroupAutoscalerInstance> instances) {
    this.instances = instances;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SetGroupAutoscalerCommand setGroupAutoscalerCommand = (SetGroupAutoscalerCommand) o;
    return Objects.equals(this.expansionTypeId, setGroupAutoscalerCommand.expansionTypeId) &&
        Objects.equals(this.minimumInstanceNumber, setGroupAutoscalerCommand.minimumInstanceNumber) &&
        Objects.equals(this.maximumInstanceNumber, setGroupAutoscalerCommand.maximumInstanceNumber) &&
        Objects.equals(this.instances, setGroupAutoscalerCommand.instances);
  }

  @Override
  public int hashCode() {
    return Objects.hash(expansionTypeId, minimumInstanceNumber, maximumInstanceNumber, instances);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SetGroupAutoscalerCommand {\n");

      sb.append("    expansionTypeId: ").append(toIndentedString(expansionTypeId)).append("\n");
    sb.append("    minimumInstanceNumber: ").append(toIndentedString(minimumInstanceNumber)).append("\n");
    sb.append("    maximumInstanceNumber: ").append(toIndentedString(maximumInstanceNumber)).append("\n");
    sb.append("    instances: ").append(toIndentedString(instances)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

