/*
 * Oktawave API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.oktawave.api.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.threeten.bp.OffsetDateTime;

import java.util.Objects;

/**
 * Ticket representing operation on service eg. instance, disk
 */
@ApiModel(description = "Ticket representing operation on service eg. instance, disk")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-04-25T12:05:03.973+02:00")
public class Ticket {
  @SerializedName("Id")
  private Long id = null;

  @SerializedName("CreationDate")
  private OffsetDateTime creationDate = null;

  @SerializedName("CreationUser")
  private UserResource creationUser = null;

  @SerializedName("EndDate")
  private OffsetDateTime endDate = null;

  @SerializedName("Status")
  private DictionaryItem status = null;

  @SerializedName("OperationType")
  private DictionaryItem operationType = null;

  @SerializedName("ObjectId")
  private Integer objectId = null;

  @SerializedName("ObjectType")
  private DictionaryItem objectType = null;

  @SerializedName("ObjectName")
  private String objectName = null;

  @SerializedName("Progress")
  private Integer progress = null;

  public Ticket id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * ID
   * @return id
  **/
  @ApiModelProperty(value = "ID")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public Ticket creationDate(OffsetDateTime creationDate) {
    this.creationDate = creationDate;
    return this;
  }

   /**
   * Creation date
   * @return creationDate
  **/
  @ApiModelProperty(value = "Creation date")
  public OffsetDateTime getCreationDate() {
    return creationDate;
  }

  public void setCreationDate(OffsetDateTime creationDate) {
    this.creationDate = creationDate;
  }

  public Ticket creationUser(UserResource creationUser) {
    this.creationUser = creationUser;
    return this;
  }

   /**
   * User who created the ticket
   * @return creationUser
  **/
  @ApiModelProperty(value = "User who created the ticket")
  public UserResource getCreationUser() {
    return creationUser;
  }

  public void setCreationUser(UserResource creationUser) {
    this.creationUser = creationUser;
  }

  public Ticket endDate(OffsetDateTime endDate) {
    this.endDate = endDate;
    return this;
  }

   /**
   * End date of operation
   * @return endDate
  **/
  @ApiModelProperty(value = "End date of operation")
  public OffsetDateTime getEndDate() {
    return endDate;
  }

  public void setEndDate(OffsetDateTime endDate) {
    this.endDate = endDate;
  }

  public Ticket status(DictionaryItem status) {
    this.status = status;
    return this;
  }

   /**
   * Status
   * @return status
  **/
  @ApiModelProperty(value = "Status")
  public DictionaryItem getStatus() {
    return status;
  }

  public void setStatus(DictionaryItem status) {
    this.status = status;
  }

  public Ticket operationType(DictionaryItem operationType) {
    this.operationType = operationType;
    return this;
  }

   /**
   * Operation type
   * @return operationType
  **/
  @ApiModelProperty(value = "Operation type")
  public DictionaryItem getOperationType() {
    return operationType;
  }

  public void setOperationType(DictionaryItem operationType) {
    this.operationType = operationType;
  }

  public Ticket objectId(Integer objectId) {
    this.objectId = objectId;
    return this;
  }

   /**
   * Object identifier on which the operation is performed
   * @return objectId
  **/
  @ApiModelProperty(value = "Object identifier on which the operation is performed")
  public Integer getObjectId() {
    return objectId;
  }

  public void setObjectId(Integer objectId) {
    this.objectId = objectId;
  }

  public Ticket objectType(DictionaryItem objectType) {
    this.objectType = objectType;
    return this;
  }

   /**
   * Object type
   * @return objectType
  **/
  @ApiModelProperty(value = "Object type")
  public DictionaryItem getObjectType() {
    return objectType;
  }

  public void setObjectType(DictionaryItem objectType) {
    this.objectType = objectType;
  }

  public Ticket objectName(String objectName) {
    this.objectName = objectName;
    return this;
  }

   /**
   * Object name
   * @return objectName
  **/
  @ApiModelProperty(value = "Object name")
  public String getObjectName() {
    return objectName;
  }

  public void setObjectName(String objectName) {
    this.objectName = objectName;
  }

  public Ticket progress(Integer progress) {
    this.progress = progress;
    return this;
  }

   /**
   * Operation progress
   * @return progress
  **/
  @ApiModelProperty(value = "Operation progress")
  public Integer getProgress() {
    return progress;
  }

  public void setProgress(Integer progress) {
    this.progress = progress;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Ticket ticket = (Ticket) o;
    return Objects.equals(this.id, ticket.id) &&
        Objects.equals(this.creationDate, ticket.creationDate) &&
        Objects.equals(this.creationUser, ticket.creationUser) &&
        Objects.equals(this.endDate, ticket.endDate) &&
        Objects.equals(this.status, ticket.status) &&
        Objects.equals(this.operationType, ticket.operationType) &&
        Objects.equals(this.objectId, ticket.objectId) &&
        Objects.equals(this.objectType, ticket.objectType) &&
        Objects.equals(this.objectName, ticket.objectName) &&
        Objects.equals(this.progress, ticket.progress);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, creationDate, creationUser, endDate, status, operationType, objectId, objectType, objectName, progress);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Ticket {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    creationDate: ").append(toIndentedString(creationDate)).append("\n");
    sb.append("    creationUser: ").append(toIndentedString(creationUser)).append("\n");
    sb.append("    endDate: ").append(toIndentedString(endDate)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    operationType: ").append(toIndentedString(operationType)).append("\n");
    sb.append("    objectId: ").append(toIndentedString(objectId)).append("\n");
    sb.append("    objectType: ").append(toIndentedString(objectType)).append("\n");
    sb.append("    objectName: ").append(toIndentedString(objectName)).append("\n");
    sb.append("    progress: ").append(toIndentedString(progress)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

