/*
 * Oktawave API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.oktawave.api.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * Instance IP configuration update command
 */
@ApiModel(description = "Instance IP configuration update command")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-02-03T15:23:33.358+01:00")
public class UpdateIpCommand {
  @SerializedName("SetStatic")
  private Boolean setStatic = null;

  @SerializedName("Comment")
  private String comment = null;

  @SerializedName("RestoreRevDns")
  private Boolean restoreRevDns = null;

  @SerializedName("RestoreRevDnsV6")
  private Boolean restoreRevDnsV6 = null;

  @SerializedName("RevDns")
  private String revDns = null;

  @SerializedName("RevDnsV6")
  private String revDnsV6 = null;

  public UpdateIpCommand setStatic(Boolean setStatic) {
    this.setStatic = setStatic;
    return this;
  }

   /**
   * IP should be static
   * @return setStatic
  **/
  @ApiModelProperty(value = "IP should be static")
  public Boolean isSetStatic() {
    return setStatic;
  }

  public void setSetStatic(Boolean setStatic) {
    this.setStatic = setStatic;
  }

  public UpdateIpCommand comment(String comment) {
    this.comment = comment;
    return this;
  }

   /**
   * IP comment
   * @return comment
  **/
  @ApiModelProperty(value = "IP comment")
  public String getComment() {
    return comment;
  }

  public void setComment(String comment) {
    this.comment = comment;
  }

  public UpdateIpCommand restoreRevDns(Boolean restoreRevDns) {
    this.restoreRevDns = restoreRevDns;
    return this;
  }

   /**
   * Restore default value for revDNS IPv4
   * @return restoreRevDns
  **/
  @ApiModelProperty(value = "Restore default value for revDNS IPv4")
  public Boolean isRestoreRevDns() {
    return restoreRevDns;
  }

  public void setRestoreRevDns(Boolean restoreRevDns) {
    this.restoreRevDns = restoreRevDns;
  }

  public UpdateIpCommand restoreRevDnsV6(Boolean restoreRevDnsV6) {
    this.restoreRevDnsV6 = restoreRevDnsV6;
    return this;
  }

   /**
   * Restore default value for revDNS IPv6
   * @return restoreRevDnsV6
  **/
  @ApiModelProperty(value = "Restore default value for revDNS IPv6")
  public Boolean isRestoreRevDnsV6() {
    return restoreRevDnsV6;
  }

  public void setRestoreRevDnsV6(Boolean restoreRevDnsV6) {
    this.restoreRevDnsV6 = restoreRevDnsV6;
  }

  public UpdateIpCommand revDns(String revDns) {
    this.revDns = revDns;
    return this;
  }

   /**
   * revDNS for IPv4
   * @return revDns
  **/
  @ApiModelProperty(value = "revDNS for IPv4")
  public String getRevDns() {
    return revDns;
  }

  public void setRevDns(String revDns) {
    this.revDns = revDns;
  }

  public UpdateIpCommand revDnsV6(String revDnsV6) {
    this.revDnsV6 = revDnsV6;
    return this;
  }

   /**
   * revDNS for IPv6
   * @return revDnsV6
  **/
  @ApiModelProperty(value = "revDNS for IPv6")
  public String getRevDnsV6() {
    return revDnsV6;
  }

  public void setRevDnsV6(String revDnsV6) {
    this.revDnsV6 = revDnsV6;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateIpCommand updateIpCommand = (UpdateIpCommand) o;
    return Objects.equals(this.setStatic, updateIpCommand.setStatic) &&
        Objects.equals(this.comment, updateIpCommand.comment) &&
        Objects.equals(this.restoreRevDns, updateIpCommand.restoreRevDns) &&
        Objects.equals(this.restoreRevDnsV6, updateIpCommand.restoreRevDnsV6) &&
        Objects.equals(this.revDns, updateIpCommand.revDns) &&
        Objects.equals(this.revDnsV6, updateIpCommand.revDnsV6);
  }

  @Override
  public int hashCode() {
    return Objects.hash(setStatic, comment, restoreRevDns, restoreRevDnsV6, revDns, revDnsV6);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateIpCommand {\n");

      sb.append("    setStatic: ").append(toIndentedString(setStatic)).append("\n");
    sb.append("    comment: ").append(toIndentedString(comment)).append("\n");
    sb.append("    restoreRevDns: ").append(toIndentedString(restoreRevDns)).append("\n");
    sb.append("    restoreRevDnsV6: ").append(toIndentedString(restoreRevDnsV6)).append("\n");
    sb.append("    revDns: ").append(toIndentedString(revDns)).append("\n");
    sb.append("    revDnsV6: ").append(toIndentedString(revDnsV6)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

