/*
 * Oktawave API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package client.model.account;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * Create SSH key command
 */
@ApiModel(description = "Create SSH key command")
public class CreateSshKeyCommand {
  @SerializedName("name")
  private String sshKeyName = null;

  @SerializedName("public_key")
  private String sshKey = null;

  public CreateSshKeyCommand sshKeyName(String sshKeyName) {
    this.sshKeyName = sshKeyName;
    return this;
  }

   /**
   * Name of SSH key
   * @return sshKeyName
  **/
  @ApiModelProperty(required = true, value = "Name of SSH key")
  public String getSshKeyName() {
    return sshKeyName;
  }

  public void setSshKeyName(String sshKeyName) {
    this.sshKeyName = sshKeyName;
  }

  public CreateSshKeyCommand sshKey(String sshKey) {
    this.sshKey = sshKey;
    return this;
  }

   /**
   * SSH key
   * @return sshKey
  **/
  @ApiModelProperty(required = true, value = "SSH key")
  public String getSshKey() {
    return sshKey;
  }

  public void setSshKey(String sshKey) {
    this.sshKey = sshKey;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateSshKeyCommand createSshKeyCommand = (CreateSshKeyCommand) o;
    return Objects.equals(this.sshKeyName, createSshKeyCommand.sshKeyName) &&
        Objects.equals(this.sshKey, createSshKeyCommand.sshKey);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sshKeyName, sshKey);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateSshKeyCommand {\n");

      sb.append("    sshKeyName: ").append(toIndentedString(sshKeyName)).append("\n");
    sb.append("    sshKey: ").append(toIndentedString(sshKey)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

